SHARED: &SHARED
  store: tumblerandco.myshopify.com
  password: shptka_500531cdb3451ed4d3392f5a845b1228
  bucket_size: 40
  refill_rate: 2
  timeout: 60s
  ignore_files:
    - "*.swp"
    - "*~"
    - ".idea"
    - "checkout-script.liquid"

development:
  <<: *SHARED
  theme_id: '136100774135'

production:
  <<: *SHARED
  readonly: true
  theme_id: '137651388663'
